import { Product } from '@/app/actions/recommendation';

export const MOCK_PRODUCTS: Product[] = [
  // Cleansers
  {
    id: '1',
    name: 'Low pH Good Morning Gel Cleanser',
    brand: 'COSRX',
    description: 'A gentle gel cleanser that maintains skin\'s optimal pH level.',
    category: 'cleanser',
    skin_type_target: ['oily', 'combination', 'normal'],
    concern_target: ['acne', 'texture'],
    sensitivity_safe: true,
    texture: 'gel',
    is_occlusive: false,
    key_actives: ['tea tree', 'bha'],
    climate_target: ['humid', 'tropical', 'air-conditioned', 'dry'],
    affiliate_platform: 'Shopee',
    affiliate_url: 'https://shopee.com.my/COSRX-Low-pH-Good-Morning-Gel-Cleanser-i.skinsync-af',
    fallback_url: 'https://shopee.com.my/search?keyword=cosrx%20low%20ph%20cleanser',
    image_url: '',
  },
  {
    id: '2',
    name: 'Toleriane Hydrating Gentle Cleanser',
    brand: 'La Roche-Posay',
    description: 'A soap-free cleanser that removes impurities while respecting the skin barrier.',
    category: 'cleanser',
    skin_type_target: ['dry', 'normal'],
    concern_target: [],
    sensitivity_safe: true,
    texture: 'lotion',
    is_occlusive: false,
    key_actives: ['ceramide', 'niacinamide'],
    climate_target: ['dry', 'air-conditioned'],
    affiliate_platform: 'Lazada',
    affiliate_url: 'https://lazada.com.my/products/lrp-toleriane-hydrating-cleanser.skinsync-af',
    fallback_url: 'https://lazada.com.my/catalog/?q=la%20roche%20posay%20toleriane%20cleanser',
    image_url: '',
  },
  {
    id: '3',
    name: 'Heartleaf Pore Control Cleansing Oil',
    brand: 'Anua',
    description: 'A lightweight cleansing oil that dissolves sebum and prepares congested pores.',
    category: 'cleanser',
    skin_type_target: ['oily', 'combination'],
    concern_target: ['pores', 'acne'],
    sensitivity_safe: true,
    texture: 'liquid',
    is_occlusive: false,
    key_actives: ['heartleaf'],
    climate_target: ['humid', 'tropical'],
    affiliate_platform: 'TikTok Shop',
    affiliate_url: 'https://shop.tiktok.com/view/product/anua-heartleaf-cleansing-oil.skinsync-af',
    fallback_url: 'https://shop.tiktok.com/search?q=anua%20heartleaf%20cleansing%20oil',
    image_url: '',
  },

  // Toners
  {
    id: '4',
    name: 'Heartleaf 77% Soothing Toner',
    brand: 'Anua',
    description: 'A fermented heartleaf toner that calms irritation and hydrates without residue.',
    category: 'toner',
    skin_type_target: ['oily', 'combination', 'normal', 'dry'],
    concern_target: ['texture', 'dullness'],
    sensitivity_safe: true,
    texture: 'liquid',
    is_occlusive: false,
    key_actives: ['heartleaf', 'panthenol'],
    climate_target: ['humid', 'tropical', 'air-conditioned', 'dry'],
    affiliate_platform: 'TikTok Shop',
    affiliate_url: 'https://shop.tiktok.com/view/product/anua-heartleaf-77-toner.skinsync-af',
    fallback_url: 'https://shop.tiktok.com/search?q=anua%20heartleaf%2077%20toner',
    image_url: '',
  },
  {
    id: '5',
    name: 'AHA/BHA Clarifying Treatment Toner',
    brand: 'COSRX',
    description: 'An exfoliating toner that clears congested pores and refines texture.',
    category: 'toner',
    skin_type_target: ['oily', 'combination'],
    concern_target: ['acne', 'pores', 'texture'],
    sensitivity_safe: false,
    texture: 'liquid',
    is_occlusive: false,
    key_actives: ['aha', 'bha'],
    climate_target: ['humid', 'tropical'],
    affiliate_platform: 'Shopee',
    affiliate_url: 'https://shopee.com.my/COSRX-AHA-BHA-Clarifying-Toner-i.skinsync-af',
    fallback_url: 'https://shopee.com.my/search?keyword=cosrx%20aha%20bha%20toner',
    image_url: '',
  },
  {
    id: '6',
    name: 'Serozinc',
    brand: 'La Roche-Posay',
    description: 'A zinc-infused mattifying mist that soothes and purifies oily, blemish-prone skin.',
    category: 'toner',
    skin_type_target: ['oily', 'combination', 'normal'],
    concern_target: [],
    sensitivity_safe: true,
    texture: 'liquid',
    is_occlusive: false,
    key_actives: ['zinc'],
    climate_target: ['humid', 'tropical', 'air-conditioned'],
    affiliate_platform: 'Lazada',
    affiliate_url: 'https://lazada.com.my/products/lrp-serozinc.skinsync-af',
    fallback_url: 'https://lazada.com.my/catalog/?q=la%20roche%20posay%20serozinc',
    image_url: '',
  },

  // Serums
  {
    id: '7',
    name: 'Peach 70% Niacinamide Serum',
    brand: 'Anua',
    description: 'A brightening serum with 70% peach extract and niacinamide for uneven tone and pores.',
    category: 'serum',
    skin_type_target: ['oily', 'combination', 'normal'],
    concern_target: ['pigmentation', 'pores'],
    sensitivity_safe: true,
    texture: 'gel',
    is_occlusive: false,
    key_actives: ['niacinamide'],
    climate_target: ['humid', 'tropical'],
    affiliate_platform: 'TikTok Shop',
    affiliate_url: 'https://shop.tiktok.com/view/product/anua-peach-niacinamide-serum.skinsync-af',
    fallback_url: 'https://shop.tiktok.com/search?q=anua%20peach%2070%20niacinamide%20serum',
    image_url: '',
  },
  {
    id: '8',
    name: 'The Vitamin C 23 Serum',
    brand: 'COSRX',
    description: 'A stabilized vitamin C serum that targets dullness and pigmentation.',
    category: 'serum',
    skin_type_target: ['normal', 'combination', 'oily'],
    concern_target: ['pigmentation', 'dullness'],
    sensitivity_safe: false,
    texture: 'liquid',
    is_occlusive: false,
    key_actives: ['vitamin c'],
    climate_target: ['humid', 'tropical', 'air-conditioned'],
    affiliate_platform: 'Shopee',
    affiliate_url: 'https://shopee.com.my/COSRX-Vitamin-C-23-Serum-i.skinsync-af',
    fallback_url: 'https://shopee.com.my/search?keyword=cosrx%20vitamin%20c%2023%20serum',
    image_url: '',
  },
  {
    id: '9',
    name: '5X Ceramide Barrier Repair Serum',
    brand: 'Skintific',
    description: 'A serum that focuses on repairing and maintaining the skin barrier.',
    category: 'serum',
    skin_type_target: ['dry', 'combination', 'normal'],
    concern_target: ['texture'],
    sensitivity_safe: true,
    texture: 'lotion',
    is_occlusive: false,
    key_actives: ['ceramide'],
    climate_target: ['dry', 'air-conditioned'],
    affiliate_platform: 'Shopee',
    affiliate_url: 'https://shopee.com.my/Skintific-5X-Ceramide-Serum-i.skinsync-af',
    fallback_url: 'https://shopee.com.my/search?keyword=skintific%20ceramide%20serum',
    image_url: '',
  },

  // Moisturizers
  {
    id: '10',
    name: 'Heartleaf Quercetinol Pore Deep Cleansing Gel Cream',
    brand: 'Anua',
    description: 'An oil-free gel-cream that hydrates without clogging pores in humid weather.',
    category: 'moisturizer',
    skin_type_target: ['oily', 'combination'],
    concern_target: ['pores', 'texture'],
    sensitivity_safe: true,
    texture: 'gel',
    is_occlusive: false,
    key_actives: ['heartleaf', 'niacinamide'],
    climate_target: ['humid', 'tropical'],
    affiliate_platform: 'TikTok Shop',
    affiliate_url: 'https://shop.tiktok.com/view/product/anua-heartleaf-gel-cream.skinsync-af',
    fallback_url: 'https://shop.tiktok.com/search?q=anua%20heartleaf%20gel%20cream',
    image_url: '',
  },
  {
    id: '11',
    name: 'Toleriane Sensitive Riche',
    brand: 'La Roche-Posay',
    description: 'A rich, ceramide-based cream for dry and reactive skin in air-conditioned environments.',
    category: 'moisturizer',
    skin_type_target: ['dry', 'normal'],
    concern_target: ['aging'],
    sensitivity_safe: true,
    texture: 'cream',
    is_occlusive: true,
    key_actives: ['ceramide', 'niacinamide'],
    climate_target: ['dry', 'air-conditioned'],
    affiliate_platform: 'Lazada',
    affiliate_url: 'https://lazada.com.my/products/lrp-toleriane-sensitive-riche.skinsync-af',
    fallback_url: 'https://lazada.com.my/catalog/?q=la%20roche%20posay%20toleriane%20riche',
    image_url: '',
  },
  {
    id: '12',
    name: 'Oil-Free Ultra-Moisturizing Lotion',
    brand: 'COSRX',
    description: 'A weightless lotion with birch sap that hydrates without heaviness.',
    category: 'moisturizer',
    skin_type_target: ['oily', 'combination'],
    concern_target: [],
    sensitivity_safe: true,
    texture: 'lotion',
    is_occlusive: false,
    key_actives: ['birch sap'],
    climate_target: ['humid', 'tropical', 'air-conditioned'],
    affiliate_platform: 'Shopee',
    affiliate_url: 'https://shopee.com.my/COSRX-Oil-Free-Moisturizing-Lotion-i.skinsync-af',
    fallback_url: 'https://shopee.com.my/search?keyword=cosrx%20oil%20free%20lotion',
    image_url: '',
  },

  // Sunscreens
  {
    id: '13',
    name: 'Relief Sun: Rice + Probiotics',
    brand: 'Beauty of Joseon',
    description: 'A lightweight, no white cast sunscreen that hydrates while protecting.',
    category: 'sunscreen',
    skin_type_target: ['dry', 'normal'],
    concern_target: ['aging'],
    sensitivity_safe: true,
    texture: 'lotion',
    is_occlusive: false,
    key_actives: ['niacinamide'],
    climate_target: ['humid', 'tropical', 'dry'],
    affiliate_platform: 'Shopee',
    affiliate_url: 'https://shopee.com.my/Beauty-of-Joseon-Relief-Sun-i.skinsync-af',
    fallback_url: 'https://shopee.com.my/search?keyword=beauty%20of%20joseon%20relief%20sun',
    image_url: '',
  },
  {
    id: '14',
    name: 'Anthelios UVMune 400 Invisible Fluid',
    brand: 'La Roche-Posay',
    description: 'A fast-absorbing, non-comedogenic broad-spectrum fluid built for daily tropical exposure.',
    category: 'sunscreen',
    skin_type_target: ['oily', 'combination', 'normal'],
    concern_target: [],
    sensitivity_safe: true,
    texture: 'liquid',
    is_occlusive: false,
    key_actives: [],
    climate_target: ['humid', 'tropical', 'air-conditioned', 'dry'],
    affiliate_platform: 'Lazada',
    affiliate_url: 'https://lazada.com.my/products/lrp-anthelios-uvmune-400.skinsync-af',
    fallback_url: 'https://lazada.com.my/catalog/?q=la%20roche%20posay%20anthelios%20uvmune',
    image_url: '',
  },
  {
    id: '15',
    name: 'Aloe Soothing Sun Cream',
    brand: 'COSRX',
    description: 'A gel-cream sunscreen with aloe that stays lightweight under humidity.',
    category: 'sunscreen',
    skin_type_target: ['oily', 'combination', 'normal'],
    concern_target: [],
    sensitivity_safe: true,
    texture: 'gel',
    is_occlusive: false,
    key_actives: ['aloe'],
    climate_target: ['humid', 'tropical'],
    affiliate_platform: 'TikTok Shop',
    affiliate_url: 'https://shop.tiktok.com/view/product/cosrx-aloe-sun-cream.skinsync-af',
    fallback_url: 'https://shop.tiktok.com/search?q=cosrx%20aloe%20soothing%20sun%20cream',
    image_url: '',
  },
];
