import { Product } from '@/app/actions/recommendation';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Low pH Good Morning Gel Cleanser',
    brand: 'COSRX',
    description: 'A gentle gel cleanser that maintains skin\'s optimal pH level.',
    price: 45.00,
    category: 'cleanser',
    skin_type_target: ['oily', 'combination', 'normal'],
    concern_target: ['acne', 'texture'],
    sensitivity_safe: true,
    stripe_price_id: 'price_mock_cleanser',
    subscription_discount_percent: 10,
    image_url: '',
  },
  {
    id: '2',
    name: 'CoalFace Soap',
    brand: 'Kayman Beauty',
    description: 'A deep cleansing soap with activated charcoal and honey.',
    price: 35.00,
    category: 'cleanser',
    skin_type_target: ['oily', 'combination'],
    concern_target: ['acne', 'pores'],
    sensitivity_safe: false,
    stripe_price_id: 'price_mock_cleanser_local',
    subscription_discount_percent: 15,
    image_url: '',
  },
  {
    id: '3',
    name: 'Cera-Mila Toner',
    brand: 'Tatagaltier',
    description: 'Milky toner with ceramides to hydrate and strengthen skin barrier.',
    price: 79.00,
    category: 'toner',
    skin_type_target: ['dry', 'normal', 'combination'],
    concern_target: ['dullness', 'texture'],
    sensitivity_safe: true,
    stripe_price_id: 'price_mock_toner',
    subscription_discount_percent: 20,
    image_url: '',
  },
  {
    id: '4',
    name: 'Skintific 5X Ceramide Barrier Repair Serum',
    brand: 'Skintific',
    description: 'A serum that focuses on repairing and maintaining the skin barrier.',
    price: 69.00,
    category: 'serum',
    skin_type_target: ['dry', 'combination', 'normal'],
    concern_target: ['texture'],
    sensitivity_safe: true,
    stripe_price_id: 'price_mock_serum',
    subscription_discount_percent: 15,
    image_url: '',
  },
  {
    id: '5',
    name: 'Self-Love Moisturizer',
    brand: 'Chuck\'s',
    description: 'Deeply hydrating moisturizer with oat extract and honey.',
    price: 98.00,
    category: 'moisturizer',
    skin_type_target: ['dry', 'normal'],
    concern_target: ['aging'],
    sensitivity_safe: true,
    stripe_price_id: 'price_mock_moisturizer',
    subscription_discount_percent: 15,
    image_url: '',
  },
  {
    id: '6',
    name: 'Airy Sunscreen',
    brand: 'Chuck\'s',
    description: 'Lightweight, no white cast sunscreen suitable for humid climates.',
    price: 75.00,
    category: 'sunscreen',
    skin_type_target: ['oily', 'combination', 'normal'],
    concern_target: [],
    sensitivity_safe: true,
    stripe_price_id: 'price_mock_sunscreen',
    subscription_discount_percent: 20,
    image_url: '',
  }
];
