INSERT INTO public.products
  (name, brand, description, category, skin_type_target, concern_target, sensitivity_safe, texture, is_occlusive, key_actives, climate_target, affiliate_platform, affiliate_url, fallback_url, image_url)
VALUES
-- Cleansers
('Low pH Good Morning Gel Cleanser', 'COSRX', 'A gentle gel cleanser that maintains skin''s optimal pH level.', 'cleanser', '{oily, combination, normal}', '{acne, texture}', true, 'gel', false, '{tea tree, bha}', '{humid, tropical, air-conditioned, dry}', 'Shopee', 'https://invl.me/clnntis', 'https://shopee.com.my/search?keyword=cosrx%20low%20ph%20cleanser', 'https://down-my.img.susercontent.com/file/cn-11134207-820l4-mmgyvpr96n7l69'),
('Toleriane Hydrating Gentle Cleanser', 'La Roche-Posay', 'A soap-free cleanser that removes impurities while respecting the skin barrier.', 'cleanser', '{dry, normal}', '{}', true, 'lotion', false, '{ceramide, niacinamide}', '{dry, air-conditioned}', 'Shopee', 'https://invl.me/clnntpo', 'https://lazada.com.my/catalog/?q=la%20roche%20posay%20toleriane%20cleanser', 'https://down-my.img.susercontent.com/file/sg-11134202-8258k-mq371qic737web'),
('Heartleaf Pore Control Cleansing Oil', 'Anua', 'A lightweight cleansing oil that dissolves sebum and prepares congested pores.', 'cleanser', '{oily, combination}', '{pores, acne}', true, 'liquid', false, '{heartleaf}', '{humid, tropical}', 'Shopee', 'https://invl.me/clnntr8', 'https://shop.tiktok.com/search?q=anua%20heartleaf%20cleansing%20oil', 'https://down-my.img.susercontent.com/file/my-11134207-7r98y-lxs5ryyla1d6a6'),

-- Toners
('Heartleaf 77% Soothing Toner', 'Anua', 'A fermented heartleaf toner that calms irritation and hydrates without residue.', 'toner', '{oily, combination, normal, dry}', '{texture, dullness}', true, 'liquid', false, '{heartleaf, panthenol}', '{humid, tropical, air-conditioned, dry}', 'Shopee', 'https://invl.me/clnntre', 'https://shop.tiktok.com/search?q=anua%20heartleaf%2077%20toner', 'https://down-my.img.susercontent.com/file/my-11134207-820lc-mfwg6dbd0nilef'),
('AHA/BHA Clarifying Treatment Toner', 'COSRX', 'An exfoliating toner that clears congested pores and refines texture.', 'toner', '{oily, combination}', '{acne, pores, texture}', false, 'liquid', false, '{aha, bha}', '{humid, tropical}', 'Shopee', 'https://invl.me/clnntjf', 'https://shopee.com.my/search?keyword=cosrx%20aha%20bha%20toner', 'https://down-my.img.susercontent.com/file/my-11134207-7r98u-llj4ig3ns9rh8c'),
('Serozinc', 'La Roche-Posay', 'A zinc-infused mattifying mist that soothes and purifies oily, blemish-prone skin.', 'toner', '{oily, combination, normal}', '{}', true, 'liquid', false, '{zinc}', '{humid, tropical, air-conditioned}', 'Shopee', 'https://invl.me/clnntqd', 'https://lazada.com.my/catalog/?q=la%20roche%20posay%20serozinc', 'https://down-my.img.susercontent.com/file/sg-11134207-82603-mjjg84w8qzuu71'),

-- Serums
('Peach 70% Niacinamide Serum', 'Anua', 'A brightening serum with 70% peach extract and niacinamide for uneven tone and pores.', 'serum', '{oily, combination, normal}', '{pigmentation, pores}', true, 'gel', false, '{niacinamide}', '{humid, tropical}', 'Shopee', 'https://invl.me/clnntrj', 'https://shop.tiktok.com/search?q=anua%20peach%2070%20niacinamide%20serum', 'https://down-my.img.susercontent.com/file/my-11134207-7r98y-lm4z64ocd42b65'),
('The Vitamin C 23 Serum', 'COSRX', 'A stabilized vitamin C serum that targets dullness and pigmentation.', 'serum', '{normal, combination, oily}', '{pigmentation, dullness}', false, 'liquid', false, '{vitamin c}', '{humid, tropical, air-conditioned}', 'Shopee', 'https://invl.me/clnntjg', 'https://shopee.com.my/search?keyword=cosrx%20vitamin%20c%2023%20serum', 'https://down-my.img.susercontent.com/file/sg-11134201-7rd4e-m6niee114r9oa0'),
('5X Ceramide Barrier Repair Serum', 'Skintific', 'A serum that focuses on repairing and maintaining the skin barrier.', 'serum', '{dry, combination, normal}', '{texture}', true, 'lotion', false, '{ceramide}', '{dry, air-conditioned}', 'Shopee', 'https://invl.me/clnntji', 'https://shopee.com.my/search?keyword=skintific%20ceramide%20serum', 'https://down-my.img.susercontent.com/file/my-11134207-820l9-mphu5bsuimfgbb'),

-- Moisturizers
('Anua 3+ Ceramide Panthenol Moisture Barrier Cream', 'Anua', 'A ceramide and panthenol barrier cream that hydrates without clogging pores in humid weather.', 'moisturizer', '{oily, combination}', '{pores, texture}', true, 'gel', false, '{ceramide, panthenol}', '{humid, tropical}', 'Shopee', 'https://invl.me/clnntrp', 'https://shop.tiktok.com/search?q=anua%20ceramide%20panthenol%20barrier%20cream', 'https://down-my.img.susercontent.com/file/my-11134207-7rasd-m5u6nu6ylbo309'),
('Toleriane Ultra Creme', 'La Roche-Posay', 'A rich, ceramide-based cream for dry and reactive skin in air-conditioned environments.', 'moisturizer', '{dry, normal}', '{aging}', true, 'cream', true, '{ceramide, niacinamide}', '{dry, air-conditioned}', 'Shopee', 'https://invl.me/clnntqn', 'https://lazada.com.my/catalog/?q=la%20roche%20posay%20toleriane%20ultra%20creme', 'https://down-my.img.susercontent.com/file/my-11134207-7rase-m9jxid23hmwka3'),
('Oil-Free Ultra-Moisturizing Lotion', 'COSRX', 'A weightless lotion with birch sap that hydrates without heaviness.', 'moisturizer', '{oily, combination}', '{}', true, 'lotion', false, '{birch sap}', '{humid, tropical, air-conditioned}', 'Shopee', 'https://invl.me/clnntjk', 'https://shopee.com.my/search?keyword=cosrx%20oil%20free%20lotion', 'https://down-my.img.susercontent.com/file/cn-11134207-820l4-mld93ijqszcx97'),

-- Sunscreens
('Relief Sun: Rice + Probiotics', 'Beauty of Joseon', 'A lightweight, no white cast sunscreen that hydrates while protecting.', 'sunscreen', '{dry, normal}', '{aging}', true, 'lotion', false, '{niacinamide}', '{humid, tropical, dry}', 'Shopee', 'https://invl.me/clnntjl', 'https://shopee.com.my/search?keyword=beauty%20of%20joseon%20relief%20sun', 'https://down-my.img.susercontent.com/file/cn-11134207-820l4-mpyxd1h1337l16'),
('Anthelios UVMune 400 Invisible Fluid', 'La Roche-Posay', 'A fast-absorbing, non-comedogenic broad-spectrum fluid built for daily tropical exposure.', 'sunscreen', '{oily, combination, normal}', '{}', true, 'liquid', false, '{}', '{humid, tropical, air-conditioned, dry}', 'Shopee', 'https://invl.me/clnntqw', 'https://lazada.com.my/catalog/?q=la%20roche%20posay%20anthelios%20uvmune', 'https://down-my.img.susercontent.com/file/cn-11134207-820l4-mq4mn1r7u6ma88'),
('Aloe Soothing Sun Cream', 'COSRX', 'A gel-cream sunscreen with aloe that stays lightweight under humidity.', 'sunscreen', '{oily, combination, normal}', '{}', true, 'gel', false, '{aloe}', '{humid, tropical}', 'Shopee', 'https://invl.me/clnntrq', 'https://shop.tiktok.com/search?q=cosrx%20aloe%20soothing%20sun%20cream', 'https://down-my.img.susercontent.com/file/my-11134207-7r98z-llj456bcxf8tc0');
